#!/usr/bin/python

# Make a one-pixel checkerboard.

import sys
from PIL import Image

WHITE_COLOR = (255, 255, 255, 255)
BLACK_COLOR = (0, 0, 0, 255)

def make_checkerboard(pathname, size):
    pixels = []

    for y in range(size):
        for x in range(size):
            color = WHITE_COLOR if (x + y) % 2 == 0 else BLACK_COLOR
            pixels.append(color)

    image = Image.new("RGBA", (size, size))
    image.putdata(pixels)
    image.save(pathname)

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("Usage: %s out.png size\n" % (sys.argv[0],))
        sys.exit(1)

    pathname = sys.argv[1]
    size = int(sys.argv[2])
    make_checkerboard(pathname, size)

if __name__ == "__main__":
    main()
